### ISSUE TITLE
Partition Reset Causes Xtratum Reset

### ISSUE THREAD

**Issue by m8** [lfd/XtratuM#1]
Hello, I couldn't find a more up-to-date code of xtratum on github so I'm posting it here. If a partition tries to set itself XM_WARM_RESET or XM_COLD_RESET, Xtratum reboots itself. This is not a situation we expect, we are just waiting for the partition to reset itself. It can be reproduced easily.

```c
#include <string.h>
#include <stdio.h>
#include <xm.h>
void PartitionMain(void)
{   
        XM_reset_partition(1, XM_WARM_RESET, 0);    
    	XM_write_console("hello partition 1\n",18);
}
```
Do you know if there is a more updated xtratum code?

**Comment by rralf** [comment]
Hi,

this is just a clone of XtratuM I created a while ago. Please reach out to the original authors!

Thanks

**Comment by m8** [comment]
Thanks for your reply.
